import type { TokenPattern } from "./../types/token";
export declare const SET_PATTERNS: TokenPattern[];
export declare const IF_PATTERNS: TokenPattern[];
export declare const FOREACH_PATTERNS: TokenPattern[];
export declare const SWITCH_PATTERNS: TokenPattern[];
export declare const CYCLE_PATTERNS: TokenPattern[];
export declare const INCLUDE_PATTERNS: TokenPattern[];
export declare const EXTENDS_PATTERNS: TokenPattern[];
export declare const FILTER_PATTERNS: TokenPattern[];
export declare const MACRO_PATTERNS: TokenPattern[];
export declare const IGNORE_PATTERN: TokenPattern[];
export declare const MISC_PATTERNS: TokenPattern[];
export declare const OUTPUT_PATTERN: TokenPattern[];
export declare const OPERATOR_PATTERN: TokenPattern[];
